[2025-07-22 22:33:54,085] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/opt/render/project/src/app.py", line 95, in index
    error_details=str(e),
                      ^
NameError: cannot access free variable 'e' where it is not associated with a value in enclosing scope
127.0.0.1 - - [22/Jul/2025:22:33:54 +0000] "GET / HTTP/1.1" 500 265 "-" "Go-http-client/2.0"
[2025-07-22 22:34:00,332] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/opt/render/project/src/app.py", line 95, in index
    error_details=str(e),
                      ^
NameError: cannot access free variable 'e' where it is not associated with a value in enclosing scope
127.0.0.1 - - [22/Jul/2025:22:34:00 +0000] "GET / HTTP/1.1" 500 265 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"